#define WIFI_SSID "YOURWIFI"
#define WIFI_PASSWORD "YOURPASSWORD"
#define BOT_TOKEN "YOUR TELEGRAM TOKEN"
#define CHAT_ID1 "YOUR ID1"
#define CHAT_ID2 "YOUR ID2"
#define CHAT_ID3 "YOUR ID3"
#define CHAT_ID4 "YOUR ID4"

#define LED_RELAIS 12
#define LED_GREEN 13
#define LED_BLUE 15
